Сверстана на гридах сетка для товаров в каталоге
htmlacademy-htmlcss/106057-device-33 pull request #5
Opened 2022-02-20 19:03 UTC by dobrjashka145

2022-03-01 12:46 UTC, andreysgra requested changes

2022-03-01 12:46 UTC, andreysgra commented on index.html
> +            <input class="search-field" type="text" id="search-id" name="search-text" placeholder="Поиск по сайту" disabled>
Хм-м, а почему `disabled`?

2022-03-01 12:46 UTC, andreysgra commented on index.html
> +              <button class="slider-detals uppercase-spacing base-button" href="#">Подробнее</button>
Это ссылка, так как предполагается переход на другую страницу.
![image](https://user-images.githubusercontent.com/17790771/156170085-7c360577-0354-4dbf-8d1e-d9073b704036.png)
Первоначальный вариант разметки у вас был правильным.

2022-03-01 12:46 UTC, andreysgra commented on styles/styles.css
> +  font-family: Raleway, Arial,sans-serif;
Веб-безопасны шрифт (тот, что идёт вторым по списку) можно не указывать. Достаточно указания семейства шрифтов. Об этом есть упоминание в критерии [CSS-06](https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-06)

Это не замечание, а просто ремарка.

2022-03-01 12:46 UTC, andreysgra commented on styles/styles.css
> +.base-button:focus:active {
А зачем собственно `:focus:hover` и `:focus:active`? Если пользователю нужно взаимодействовать с элементом находящимся в фокусе, то нет необходимости убирать у него обводку, которая указывает, что данный элемент в фокусе.

2022-03-01 12:46 UTC, andreysgra commented on styles/styles.css
> +.logo:focus:active {
То же, что и для `base-button`.

2022-03-01 12:46 UTC, andreysgra commented on styles/styles.css
> +.mailing-button:focus:active {
И здесь, как и для `base-button`.

2022-03-02 19:06 UTC, dobrjashka145 commented on index.html
> +              <button class="slider-detals uppercase-spacing base-button" href="#">Подробнее</button>
Исправлено, как и аналогичные кнопки на карточках товара внутренней страницы

2022-03-02 19:11 UTC, dobrjashka145 commented on styles/styles.css
> +.base-button:focus:active {
Я не знала, как правильно отображать состояния с элементом в фокусе, ориентировалась на стайлгайд. Если не надо убирать обводку, это сильно упрощает жизнь. Исправляю

2022-03-07 12:03 UTC, dobrjashka145 commented on styles/styles.css
> +.logo:focus:active {
Там, где остались focus:hover, focus:active, у меня по другому не получалось - для элемента в фокусе не отображалось то одно состояние, то другое.

2022-03-07 16:18 UTC, merged