стилизованы декоративные элементы каталога
htmlacademy-htmlcss/106057-device-33 pull request #6
Opened 2022-03-08 18:44 UTC by dobrjashka145

2022-03-09 18:41 UTC, andreysgra requested changes
В разметке каталога наблюдаются 2 семантические проблемы:
![image](https://user-images.githubusercontent.com/17790771/157505751-c3cec431-0b18-47c8-8b89-8967ba0293ee.png)
1. Тег `aside` используется для разметки второстепенного, не очень важного для страницы контента, который только косвенно связан со страницей. Блок фильтра товара - важная часть сайта и `aside` для неё не подходит. Здесь можно использовать `section` или `div`.
2. Тег `article` используется для разметки самодостаточного контента, который свободно может быть перенесён на другую страницу сайта или даже другой сайт. Смысл содержания при этом не утратится. В каталоге на разметку тегом `article` претендует карточка товара, но никак не весь блок с карточками и сортировкой. Для разметки `catalog-content` также можно использовать `section` или `div`.

---

А здесь `article` тоже не нужен
![image](https://user-images.githubusercontent.com/17790771/157509050-d5b64efe-d2fd-4c14-aff0-768f89282917.png)
Лучше заменить на `div` или `section`.

2022-03-09 18:41 UTC, andreysgra commented on catalog.html
> +          <ul class="catalog-submenu">
На мой взгляд список ссылок `catalog-submenu` стоит сделать дочерним элементом списка `nav-catalog `, то есть вложенным списком, а эти ссылки не размечать отдельным списком - ссылки должны быть частью общего списка `nav-catalog `
![image](https://user-images.githubusercontent.com/17790771/157503741-93398749-d9e3-4e1f-b35b-174221588469.png)

```
<ul class="nav-catalog uppercase-spacing">
  <li>
    <a href="#">Каталог товаров</a>

    <ul class="catalog-submenu">
      <!-- список подменю -->
    </ul>
  </li>
  <li>
    <a href="#">Доставка</a>
  <li>
  <!-- и так далее -->
</ul>
```

Это больше рекомендация, чем замечание.

2022-03-09 18:41 UTC, andreysgra commented on catalog.html
> +            <li class="submenu-item submenu-copter">
Не совсем понятна логика добавления дополнительных классов типа `submenu-virtual` элементу списка. Одна ссылка ничем не отличается от другой, стало быть свойства у них одинаковые.

2022-03-09 18:41 UTC, andreysgra commented on catalog.html
> +              <a class="current" href="#">Доставка</a>
А зачем здесь `current`? Это страница каталога, а не доставки.

2022-03-09 18:41 UTC, andreysgra commented on styles/styles.css
> +}
Свойство `border` увеличивает геометрию HTML элемента, так как учитывается при вычислении размеров. Из-за этого происходит смещение контента вокруг. Для эффекта рамки нужно воспользоваться свойством, которое не влияет на геометрию, например `box-shadow` или `outline`.

2022-03-09 18:41 UTC, andreysgra commented on styles/styles.css
>  }
Кнопки переключения слайдов лучше не позиционировать по отдельности, а сделать над ними обёртку, которая будет флекс-контейнером и позиционировать уже саму обёртку.

2022-03-09 18:41 UTC, andreysgra commented on styles/styles.css
> +}
Не ошибка у вас, но мой совет: свойство `background` составное и содержит в себе много отдельных свойств, поэтому по возможности лучше использовать не его, а отдельные свойства из которых оно состоит. По событию `hover` вам нужно изменить позицию изображения, а остальные параметры остаются неизменными. Так как вы используете `background`, то вам приходится повторять все параметры. Но если бы вместо `background` вы записали всё при помощи `background-image`, `background-color`, `background-position`, то в `hover` вам нужно было бы изменить только `background-position`.

2022-03-09 18:41 UTC, andreysgra commented on styles/styles.css
> +  font-family: Raleway;
[CSS-06](https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-06) - не указано типовое семейство для шрифта.

2022-03-10 15:27 UTC, dobrjashka145 commented on catalog.html
> +            <li class="submenu-item submenu-copter">
Эти классы добавлены для описания grid-template-areas. Но, может, можно менее громоздко, например, через nth()-child как-то по другому?

2022-03-10 15:29 UTC, dobrjashka145 commented on catalog.html
> +              <a class="current" href="#">Доставка</a>
Осталось от проверки состояния, я исправила

2022-03-10 15:31 UTC, dobrjashka145 commented on styles/styles.css
> +}
Исправлено

2022-03-10 16:10 UTC, dobrjashka145 commented on styles/styles.css
>  }
Исправлено

2022-03-10 17:05 UTC, dobrjashka145 commented on styles/styles.css
> +}
Исправлено

2022-03-10 17:06 UTC, dobrjashka145 commented on styles/styles.css
> +  font-family: Raleway;
Исправлено

2022-03-11 07:02 UTC, andreysgra commented on catalog.html
> +            <li class="submenu-item submenu-copter">
> Эти классы добавлены для описания grid-template-areas.

Сразу не обратил на это внимания. Пусть останется, как есть. Через `:nth()-child` делать не стоит, так как это структурный псевдо селектор, а значит он завязан на порядок элементов DOM-дерева. Стоит добавить / убрать какой-нибудь пункт меню и вся раскладка изменится.

Здесь можно было бы изменить разметку и добавить вложенные списки:
![image](https://user-images.githubusercontent.com/17790771/157818454-6cbfddcb-a6a0-4d85-a406-d6ee7f56ff06.png)
Каждый список - это отдельная категория товаров.

2022-03-11 07:04 UTC, merged